##SOLICITA AL USUARIO QUE INGRESE DOS NUMEROS
num1 = float(input("INGRESE EL PRIMER NUMERO: "))
num2 = float(input("INGRESE EL SEGUNDO NUMERO: "))
print()
#REALIZA LA MULTIPLICACION DE LOS DOS NUMEROS
resultado = num1 * num2
#MUESTRA EL RESULTADO DE LA MULTIPLICACION 
print("EL RESULTADO DE LA MULTIPLICACION DE {} Y {} ES: {}".format(num1,num2,resultado))
